system:
  use-db: true
  use-redis: true
  use-nsq: true

customize-config:
  lookup-addr: "141.193.158.226:4161"
  lookup-auth-mode: ""
  lookup-auth-user: ""
  lookup-auth-password: ""
  nsqd-addr: "141.193.158.226:4150"
  local-cache-size: "1000"

mysql:
  path: 8.222.220.235
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: group2
  username: test
  password: L@qun888...
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
  debug: true

nsq-config:
  lookup-addr: "141.193.158.226:4161"
  lookup-auth-mode: ""
  lookup-auth-user: ""
  lookup-auth-password: ""
  nsqd-addr: "141.193.158.226:4150"
  local-cache-size: "1000"

zap:
  level: info
  prefix: '[mars-group] '
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: false
  log-in-console: true

redis:
  db: 3
  addr: 103.84.86.50:6379
  password: "redis"